### ISSUE TITLE
Code for generating examples using regex

### ISSUE THREAD

**Issue by ciuji** [xiye17/StructuredRegex#3]
Hi!

Thanks for your code and dataset!
Do you by any chance share the code for generating positive and negative examples under specific regex? (As Section3.1 Positive/Negative Example Generation introduced in the paper)
I want to generate more examples of given regexes.

Thanks!
Chaoji Zuo

**Comment by xiye17** [comment]
I ll try to find the tool and get back to you later.

**Comment by xiye17** [comment]
Could you send me an email at xiye17@gmail.com . I ll send you the tool.
